apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk012-ui-second
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk012-ui-second
  template:
    metadata:
      labels:
        app: sk012-ui-second
    spec:
      containers:
      - name: sk012-ui-second
        image: amdp-registry.skala-ai.com/skala25a/sk012-my-second-app:1.0.kaniko-docker-20-abe1601a3af1
        ports:
        - containerPort: 80
