apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk012-ui
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk012-ui
  template:
    metadata:
      labels:
        app: sk012-ui
    spec:
      containers:
      - name: sk012-ui
        image: amdp-registry.skala-ai.com/skala25a/sk012-ui:1.0.1
        ports:
        - containerPort: 80
